"""Ibis code generator for typedata entities.

Generates Python modules containing plain Ibis functions (no Hamilton)
that transform entity data through source, prep, dimension, and snapshot layers.
"""

from __future__ import annotations

from pathlib import Path

from typedata.core.entity import Entity
from typedata.core.source import (
    AggregationSource,
    EventAggregationSource,
    TableSource,
    UnionSource,
)

IBIS_TYPE_MAP: dict[str, str] = {
    "timestamp": "timestamp",
    "timestamptz": "timestamp",
    "boolean": "boolean",
    "integer": "int64",
    "bigint": "int64",
    "int64": "int64",
    "float": "float64",
    "double": "float64",
    "float64": "float64",
    "decimal": "decimal",
    "numeric": "decimal",
    "string": "string",
    "text": "string",
    "date": "date",
}


class IbisCodeGenerator:
    """Generate Ibis Python modules from entity definitions."""

    def __init__(self, entity: Entity) -> None:
        self.entity = entity
        self.entity_name = entity.name

    def _generate_imports(self) -> str:
        """Generate module header with imports (no Hamilton)."""
        return f'''"""{self.entity_name} entity transformations.

Auto-generated by typedata.generate() -- DO NOT EDIT.
Source entity: {self.entity_name}
"""

import os

import ibis
'''

    def _bind_expression(self, expr: str) -> str:
        """Bind column references to table variable 't'.

        If the expression already references t. or starts with ibis. or (,
        pass it through unchanged. Otherwise prefix with t.
        """
        if "t." in expr:
            return expr
        if expr.startswith("ibis.") or expr.startswith("("):
            return expr
        return f"t.{expr}"

    def _generate_source_functions(self) -> str:
        """Generate source reader functions, dispatching by source type."""
        source = self.entity.source
        if source is None:
            return ""

        if isinstance(source, UnionSource):
            return self._generate_union_source_functions(source)
        elif isinstance(source, (TableSource, EventAggregationSource)):
            return self._generate_single_source_function(source)
        elif isinstance(source, AggregationSource):
            return self._generate_aggregation_source_function(source)
        else:
            return ""

    def _generate_single_source_function(
        self, source: TableSource | EventAggregationSource
    ) -> str:
        """Generate a single source function with backend switching."""
        name = self.entity_name

        # Build DuckDB path
        if source.duckdb_path:
            duckdb_path = source.duckdb_path
        else:
            duckdb_path = f"~/timo-data/{source.table}/**/*.parquet"

        func = f'''
def source_{name}(conn: ibis.BaseBackend, backend: str) -> ibis.Table:
    """Read {name} from configured source."""
    if backend == "duckdb":
        parquet_path = os.path.expanduser("{duckdb_path}")
        return conn.read_parquet(parquet_path)
    elif backend == "bigquery":
        return conn.table("{source.table}", database=("{source.project}", "{source.dataset}"))
    else:
        raise ValueError(f"Unsupported backend: {{backend}}")
'''
        return func

    def _generate_aggregation_source_function(self, source: AggregationSource) -> str:
        """Generate source function for aggregation from another entity."""
        name = self.entity_name
        func = f'''
def source_{name}(source_{source.source_entity}: ibis.Table) -> ibis.Table:
    """Aggregate {name} from {source.source_entity}."""
    t = source_{source.source_entity}
'''
        if source.filter_expression:
            func += f"    t = t.filter({source.filter_expression})\n"
        func += f'    return t.group_by("{source.group_by_column}")\n'
        return func

    def _generate_union_source_functions(self, source: UnionSource) -> str:
        """Generate per-source functions and a union aggregator."""
        name = self.entity_name
        parts = []

        # Generate a function for each sub-source
        sub_names = []
        for _i, sub_source in enumerate(source.sources):
            src_label = sub_source.table
            sub_name = f"source_{name}_{src_label}"
            sub_names.append(sub_name)

            if sub_source.duckdb_path:
                duckdb_path = sub_source.duckdb_path
            else:
                duckdb_path = f"~/timo-data/{sub_source.table}/**/*.parquet"

            func = f'''
def {sub_name}(conn: ibis.BaseBackend, backend: str) -> ibis.Table:
    """Read {src_label} for {name} union."""
    if backend == "duckdb":
        parquet_path = os.path.expanduser("{duckdb_path}")
        return conn.read_parquet(parquet_path)
    elif backend == "bigquery":
        return conn.table("{sub_source.table}", database=("{sub_source.project}", "{sub_source.dataset}"))
    else:
        raise ValueError(f"Unsupported backend: {{backend}}")
'''
            parts.append(func)

        # Generate union aggregator
        call_lines = ",\n        ".join(f"{sn}(conn, backend)" for sn in sub_names)
        union_func = f'''
def source_{name}(conn: ibis.BaseBackend, backend: str) -> ibis.Table:
    """Union all {name} sources."""
    parts = [
        {call_lines},
    ]
    return ibis.union(*parts)
'''
        parts.append(union_func)

        return "\n".join(parts)

    def generate_module(self) -> str:
        """Generate complete Python module source code."""
        parts = [
            self._generate_imports(),
            self._generate_source_functions(),
        ]

        if self.entity.layers.prep:
            parts.append(self._generate_prep_function())

        if self.entity.layers.dimension:
            parts.append(self._generate_dimension_function())

        if self.entity.layers.snapshot and self.entity.layers.snapshot.enabled:
            parts.append(self._generate_snapshot_function())

        return "\n\n".join(p for p in parts if p)

    def _map_ibis_type(self, type_str: str) -> str:
        """Map generic type names to Ibis type strings."""
        return IBIS_TYPE_MAP.get(type_str.lower(), type_str.lower())

    def _generate_source_transforms(self) -> str:
        """Generate Ibis code for SourceTransforms (renames, casts, divides, multiplies)."""
        source = self.entity.source
        transforms = getattr(source, "transforms", None)
        if not transforms:
            return ""

        lines = []

        # 1. Renames
        if transforms.renames:
            rename_args = ", ".join(
                f'{r.to_name}="{r.from_name}"' for r in transforms.renames
            )
            lines.append(f"    t = t.rename({rename_args})")

        # 2. Type casts
        if transforms.type_casts:
            for tc in transforms.type_casts:
                ibis_type = self._map_ibis_type(tc.target_type)
                lines.append(f'    t = t.mutate({tc.field}=t.{tc.field}.cast("{ibis_type}"))')

        # 3. Divides
        if transforms.divides:
            for d in transforms.divides:
                new_name = f"{d.field}{d.suffix}"
                ibis_type = self._map_ibis_type(d.target_type)
                lines.append(
                    f'    t = t.mutate({new_name}=(t.{d.field} / {d.divisor}).cast("{ibis_type}"))'
                )

        # 4. Multiplies
        if transforms.multiplies:
            for m in transforms.multiplies:
                new_name = f"{m.field}{m.suffix}"
                ibis_type = self._map_ibis_type(m.target_type)
                lines.append(
                    f'    t = t.mutate({new_name}=(t.{m.field} * {m.multiplier}).cast("{ibis_type}"))'
                )

        return "\n".join(lines) + "\n" if lines else ""

    def _generate_prep_function(self) -> str:
        """Generate prep layer transformation function."""
        layer = self.entity.layers.prep
        computed_cols = layer.computed_columns if layer else []

        func = f"""
def prep_{self.entity_name}(source_{self.entity_name}: ibis.Table) -> ibis.Table:
    \"\"\"Prep layer transformations for {self.entity_name}.\"\"\"
    t = source_{self.entity_name}
"""

        # Source transforms (renames, casts, divides, multiplies)
        transforms_code = self._generate_source_transforms()
        if transforms_code:
            func += "\n" + transforms_code

        # Computed columns
        if computed_cols:
            func += "\n    # Computed columns\n"
            func += "    prep = t.mutate(\n"
            for i, col in enumerate(computed_cols):
                comma = "," if i < len(computed_cols) - 1 else ","
                expr = self._bind_expression(col.expression)
                if hasattr(col, "description") and col.description:
                    func += f"        # {col.description}\n"
                func += f"        {col.name}={expr}{comma}\n"
            func += "    )\n"
            func += "    return prep\n"
        else:
            func += "    return t\n"

        return func

    def _generate_dimension_function(self) -> str:
        """Generate dimension layer function."""
        layer = self.entity.layers.dimension

        # Merge core_computed + layer computed columns
        core_computed = list(self.entity.core_computed or [])
        layer_computed = list(layer.computed_columns or []) if layer else []
        computed_cols = core_computed + layer_computed

        # Determine input parameter name
        if self.entity.layers.prep:
            input_name = f"prep_{self.entity_name}"
        else:
            input_name = f"source_{self.entity_name}"

        func = f"""
def dim_{self.entity_name}({input_name}: ibis.Table) -> ibis.Table:
    \"\"\"Dimension layer for {self.entity_name}.\"\"\"
    t = {input_name}
"""

        if computed_cols:
            func += "\n    # Apply dimension computed columns\n"
            func += "    dim = t.mutate(\n"
            for i, col in enumerate(computed_cols):
                comma = "," if i < len(computed_cols) - 1 else ","
                expr = self._bind_expression(col.expression)
                if hasattr(col, "description") and col.description:
                    func += f"        # {col.description}\n"
                func += f"        {col.name}={expr}{comma}\n"
            func += "    )\n"
            func += "    return dim\n"
        else:
            func += "    return t\n"

        return func

    def _generate_snapshot_function(self) -> str:
        """Generate snapshot layer function that delegates to apply_snapshot()."""
        snapshot = self.entity.layers.snapshot
        date_col = snapshot.date_column

        # Parse deduplication ordering
        dedup_parts = snapshot.deduplication_order_by.strip().split()
        dedup_col = dedup_parts[0]
        dedup_desc = True
        if len(dedup_parts) > 1:
            dedup_desc = dedup_parts[1].upper() != "ASC"

        # Format natural_key for generated code
        nk = snapshot.natural_key
        if isinstance(nk, str):
            nk_repr = f'"{nk}"'
        else:
            nk_repr = repr(nk)

        include_validity = snapshot.include_validity_range

        # Determine input: prefer dim, then prep, then source
        if self.entity.layers.dimension:
            input_name = f"dim_{self.entity_name}"
        elif self.entity.layers.prep:
            input_name = f"prep_{self.entity_name}"
        else:
            input_name = f"source_{self.entity_name}"

        func = f"""
def snapshot_{self.entity_name}({input_name}: ibis.Table) -> ibis.Table:
    \"\"\"Snapshot layer: daily snapshot with {date_col} column.\"\"\"
    from typedata.engine.snapshot import apply_snapshot

    return apply_snapshot(
        {input_name},
        natural_key={nk_repr},
        date_column="{date_col}",
        dedup_order_by="{dedup_col}",
        dedup_descending={dedup_desc},
        include_validity_range={include_validity},
    )
"""
        return func

    def write_module(self, output_dir: Path) -> Path:
        """Write generated module to disk. Returns path to written file."""
        output_dir = Path(output_dir)
        output_dir.mkdir(parents=True, exist_ok=True)
        output_path = output_dir / f"{self.entity_name}_transforms.py"
        code = self.generate_module()
        output_path.write_text(code)
        return output_path
